hashicorp/atlas-help

- discover/community-resources.html.md
- index.html.erb
Related to: https://github.com/hashicorp/atlas/pull/420
> Add discover section to docs

- _nav.html.erb
- getting-started/deploy-fully-configured-infrastructure.html.md
- getting-started/getting-started-overview.html.md
- getting-started/layout-infrastructure.html.md
- getting-started/package-services-with-artifacts.html.md
- getting-started/run-your-application.html.md
- getting-started/transition-to-atlas.html.md
- use-cases/adopt-devops.html.md
- use-cases/hybrid-cloud-deployments.html.md
- use-cases/migrate-to-cloud.html.md
- use-cases/one-dashboard.html.md
- use-cases/one-workflow.html.md
Navigation content for tutorial and use cases
> Add prev and next nav for docs

- _nav.html.erb
- account-management/command-line-login.html.md
> Add page for command line login info

- FAQ/packer.html.md
- _nav.html.erb
> Explain where files go with packer push

- FAQ/packer.html.md
I'll add the image when I update the help commit sha in the Atlas repo
cc @pearkes @sethvargo
> Update packer docs

- getting-started/package-services-with-artifacts.html.md
I was going through the atlas tutorial and wasn't sure which file was the packer template, so I figured I'd help improve the docs!
> Adding the filename fo the packer template.

- guides/continuous-integration.html.md
Use upload CLI, give Travis CI example
> Update ci guide

- _nav.html.erb
- documentation/build-configurations.html.md
- documentation/environments.html.md
- vagrant/boxes/what.html.md
> Some Definitions

- getting-started/deploy-fully-configured-infrastructure.html.md
- getting-started/layout-infrastructure.html.md
- getting-started/package-services-with-artifacts.html.md
- getting-started/run-your-application.html.md
- guides/vagrant-box-create-and-distribute.html.md
> Update docs for new ui and navigation

- getting-started/layout-infrastructure.html.md
https://github.com/hashicorp/atlas-help/issues/32
> Fixes outdated 'remote' command instruction

- getting-started/deploy-fully-configured-infrastructure.html.md
- getting-started/layout-infrastructure.html.md
- getting-started/run-your-application.html.md
> Update guides to use terraform remote

- account-management/command-line-login.html.md
- getting-started/deploy-fully-configured-infrastructure.html.md
- getting-started/getting-started-overview.html.md
- getting-started/layout-infrastructure.html.md
- getting-started/package-services-with-artifacts.html.md
- getting-started/run-your-application.html.md
- guides/vagrant-box-create-and-distribute.html.md
Updating Atlas help content to reflect what the current Atlas UI looks like as well as some copy updates.
This must be deployed with the [Atlas images PR](https://github.com/hashicorp/atlas/pull/876) or some images may not show up.
Also need to merge https://github.com/hashicorp/atlas-examples/pull/42
> Update Atlas Help Content

- getting-started/deploy-fully-configured-infrastructure.html.md
- getting-started/layout-infrastructure.html.md
- getting-started/package-services-with-artifacts.html.md
- getting-started/run-your-application.html.md
Update copy for push commands to reference the directory they should be run in.
> Update Atlas Help copy

- packer/builds/build-environment.html.md
Adds a list of our supported packer builders.
> packer: supported builders section

- terraform/runs/starting.html.md
> Document skipping a plan

- packer/builds/notifications.html.md
- packer/builds/starting.html.md
- terraform/runs/automatic-applies.html.md
- terraform/runs/notifications.html.md
- terraform/runs/starting.html.md
- vagrant/shares/create.html.md
this is a markup only companion update to https://github.com/hashicorp/atlas/pull/1146
> unified alert styles in help section

- terraform/runs/index.html.md
@sethvargo is this the right link to use?
> fix broken auto-apply link

- intro/use-cases/continuous-deployment-of-immutable-infrastructure.html.md
This should help explain how all the atlas pieces fit together
> Explain cd in a bit more detail

- glossary.html.md
Consul Auto-join as a free features
cc @pearkes @mitchellh
> Update manged node definition

- packer/builds/troubleshooting.html.md
This adds some help docs for debugging hanging builds.
> Add help for hanging SSH builds

- not-found.html.erb
Thanks to copyedt on https://twitter.com/copyedt/status/620807196259958785
> Update contact link

- packer/builds/build-environment.html.md
Copied the verbiage from [Terraform's variables page](https://github.com/hashicorp/atlas-help/blob/b3712152dc9db11bdb9a1b526b229c7f3ad95838/terraform/runs/variables-and-configuration.html.md) to clarify Packer variable security.
> Packer builds variables security

- vagrant/boxes/catalog.html.md
> Rename Chef to Bento

- _nav.html.erb
- applications/build-pipeline.html.md
- applications/compilation.html.md
- applications/index.html.md
- applications/uploading.html.md
This is the initial set of application compilation docs.
> applications: initial docs

- packer/builds/starting.html.md
See [Slack discussion](https://hashicorp.slack.com/archives/atlas/p1442525819000879) that this feature is now 100% rolled out.
> Remove notice about Packer->GitHub Import unreleased beta feature.

- terraform/runs/starting.html.md
I think this feature is READY
cc @pearkes
> release artifact-triggered terraform runs

- packer/builds/build-environment.html.md
> update build env variables

- packer/builds/build-environment.html.md
@justincampbell is this more clear?
cc @sethvargo
> clarify packer biuld env

- applications/build-pipeline.html.md
- applications/compilation.html.md
- packer/builds/build-environment.html.md
Now available during compiles and builds.
> Add ATLAS_{APPLICATION,BUILD}_GITHUB_COMMIT_SHA

- packer/builds/troubleshooting.html.md
This documents some internal errors that will soon be displayed in the UI.
> packer: document internal errors

- _nav.html.erb
- intro/vs/ci.html.md
- intro/vs/hashicorp-tools.html.md
> Add vs ci section

- applications/build-pipeline.html.md
- applications/compilation.html.md
- packer/builds/build-environment.html.md
- terraform/runs/variables-and-configuration.html.md
This adds the new "branch" and "tag" options as well.
> Update documentation on environment variables

- packer/builds/build-environment.html.md
The base artifact injection has been rolled out to all
> removed beta warning

- _nav.html.erb
- vagrant/boxes/limits.html.md
> Add new FAQ around limits

- _nav.html.erb
- applications/notifications.html.md
> Add Application Notitications section

- _nav.html.erb
Fix for HashiCorp/roadmap issue #1271.
Fixing incorrect relative path.
/cc: @pearkes
> Fix Atlas help for packer navigation

- packer/builds/scheduling-builds.html.md
> builds: remove beta message for scheduled builds

- _nav.html.erb
- packer/builds/managing-packer-versions.html.md
- terraform/runs/managing-terraform-versions.html.md
This documents the version selection feature for Packer/Terraform.
> packer/tf: add docs for managing tool versions

- terraform/runs/variables-and-configuration.html.md
Document and discuss how to use both "Environment Variables" and "Terraform Variables" to store multi-line files in Atlas.
> Update Multi-Line Variable Docs
